### ISSUE TITLE
Error when I execute npm install?

### ISSUE THREAD

**Issue by liwenzhu** [rubenv/node-xlsx-writer#6]
I got an error when I execute npm install , do you have any solution? it seems zipper's make error? or update zipper?

275 error zipper@0.3.0 install: `make all`
275 error Exit status 2
276 error Failed at the zipper@0.3.0 install script.
276 error This is most likely a problem with the zipper package,
276 error not with npm itself.
276 error Tell the author that this fails on your system:
276 error     make all
276 error You can get their info via:
276 error     npm owner ls zipper
276 error There is likely additional logging output above.
277 error System Linux 3.8.0-35-generic
278 error command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "xlsx-writer"
279 error cwd /home/vincent/Desktop/bitbucket/calculation
280 error node -v v0.10.25
281 error npm -v 1.3.24
282 error code ELIFECYCLE
283 verbose exit [ 1, true ]

and I'm using node v0.10.25 :)

**Comment by robsegoa** [comment]
adm-zip works well!!!!
